# Generated by Django 3.0.1 on 2020-02-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentFullName', models.CharField(max_length=200)),
                ('studentDept', models.CharField(max_length=200)),
                ('studentSession', models.CharField(max_length=200)),
                ('studentSSC', models.CharField(default=0.0, max_length=5)),
                ('studentHSC', models.CharField(default=0.0, max_length=5)),
                ('studentFather', models.CharField(max_length=200)),
                ('studentMother', models.CharField(max_length=200)),
                ('studentPresentAddress', models.CharField(max_length=200)),
                ('studentPermanentAddress', models.CharField(max_length=200)),
                ('studentEmail', models.CharField(max_length=200)),
            ],
        ),
    ]
